# RSS Feed Configuration for Daily Intelligence Brief
# Each feed should specify: name, url, tags, and optionally maxItems

feeds:
  # Tech News
  - name: "Hacker News"
    url: "https://hnrss.org/frontpage"
    tags: ["tech", "news"]
    maxItems: 10

  - name: "GitHub Blog"
    url: "https://github.blog/feed/"
    tags: ["github", "dev"]
    maxItems: 5

  # DevOps & Infrastructure
  - name: "DevOps Subreddit"
    url: "https://www.reddit.com/r/devops/.rss"
    tags: ["devops", "infrastructure"]
    maxItems: 5

  - name: "Kubernetes Blog"
    url: "https://kubernetes.io/feed.xml"
    tags: ["kubernetes", "devops"]
    maxItems: 5

  # Security
  - name: "The Hacker News (Security)"
    url: "https://thehackernews.com/feeds/posts/default"
    tags: ["security", "cyber"]
    maxItems: 10

  - name: "Krebs on Security"
    url: "https://krebsonsecurity.com/feed/"
    tags: ["security", "cyber"]
    maxItems: 5

  # Development
  - name: "Dev.to"
    url: "https://dev.to/feed"
    tags: ["dev", "tutorial"]
    maxItems: 10

  - name: "CSS Tricks"
    url: "https://css-tricks.com/feed/"
    tags: ["web", "css", "frontend"]
    maxItems: 5

  # AI/ML
  - name: "Towards Data Science"
    url: "https://towardsdatascience.com/feed"
    tags: ["ai", "ml", "data"]
    maxItems: 5

  # Open Source
  - name: "Opensource.com"
    url: "https://opensource.com/feed"
    tags: ["opensource", "community"]
    maxItems: 5
